services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - ${APP_PORT}:80

  db: 
    image: ${DB_IMAGE}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: