services:
  web-s1-ti:
    build: .
    env_file:
      - .env
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    container_name: web-s1-ti-backend
    networks:
      - web-s1-ti-net

  db:
    image: ${DB_IMAGE}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - web_s1_ti_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: web-s1-ti-db
    networks:
      - web-s1-ti-net

volumes:
  web_s1_ti_db_data:

networks:
  web-s1-ti-net:
